# Copyright 2021 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

FROM python:3.11-alpine3.18

COPY enclave-vsock.py .

CMD ["/usr/local/bin/python3", "enclave-vsock.py", "--port", "5005"]
